services:
  db:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: med
  redis:
    image: redis:8.2-alpine
    restart: always
