services:
  postgres:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: med
    expose:
      - 5432
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data/

  apiservice:
    build: apiservice
    restart: always
    depends_on:
      postgres:
        condition: service_started
    expose:
      - 9042
    volumes:
    - ./volumes/researches:/researches

  web:
    build: web
    restart: always
    depends_on:
      apiservice:
        condition: service_started
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/certs:/etc/nginx/certs:ro

  inference:
    build: inference
    restart: always
    environment:
      PYTHONUNBUFFERED: 1 # для работы print
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    expose:
      - 30042
    volumes:
    - ./volumes/researches:/researches
    runtime: nvidia
    gpus: all
    privileged: true
