services:
  postgres:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: med
    ports:
      - 9432:5432
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data/

  redis:
    image: redis:8.2-alpine
    restart: always
    ports:
      - 9379:6379
    volumes:
      - ./volumes/redis:/data
